### ISSUE TITLE
memoize camelCase conversion

### ISSUE THREAD

**Issue by mhuebert** [braintripping/re-view#15]
Converting keys from `dashed-case` to `camelCase` has a nontrivial perf impact

**Comment by pedrorgirardi** [comment]
If implemented, does it enable using `dashed-case` for custom methods inside the component?

**Comment by mhuebert** [comment]
This is already implemented (just not memoized), so dashed-case should already work for custom methods. I do this a bunch in maria: https://github.com/mhuebert/maria/blob/master/editor/src/maria/editors/code.cljs#L147

**Comment by pedrorgirardi** [comment]
My bad, I misunderstood it. Even though the custom method can be declared in `dash-case`, it must be called with `camelCase`, right? I thought you were saying that we could call the method using `dash-case` too.

**Comment by mhuebert** [comment]
Oh, I see. Yeah I doubt it would ever work to use host-interop syntax with invalid javascript names, like `(.my-key obj)`

**Comment by pedrorgirardi** [comment]
Right, I see now.

**Comment by mhuebert** [comment]
Added in 2a8c9173
