### ISSUE TITLE
re-db docs

### ISSUE THREAD

**Issue by pedrorgirardi** [braintripping/re-view#17]
Which parts of the docs do you think needs more work? I would like to learn a little bit more about `re-db` and I think helping with the docs might be a good way to learn its API.

**Comment by mhuebert** [comment]
Hmm, something that might be interesting is to port/copy the README to Maria. We already have re-db loaded in the maria environment, so one should be able to `(require [re-db.d :as d])` and see if all of the examples work. 

(If you go this route, I'd recommend using dev.maria.cloud - I've made some recent improvements to the structural editing.. it should be a nicer experience, but possibly new bugs too :))

**Comment by pedrorgirardi** [comment]
It's not complete, but I had already started writing the README in Maria to try the examples :)

https://www.maria.cloud/gist/b1a6ce5464f2305c1e99e62345e246fd
