### ISSUE TITLE
Lein template?

### ISSUE THREAD

**Issue by jackrusher** [braintripping/re-view#2]
The documentation is very nice over all, but the path from nothing to a working project using `re-view` is somewhat unclear. If this project is meant primarily for cljs experts, this is probably not a problem, but I think it would be nice for non-experts if it were possible to generate a project skeleton using some variation of `lein new <template>`.

**Comment by mhuebert** [comment]
Great idea. I've added a template so you can now do

```bash
lein new re-view xyz;
cd xyz;
lein figwheel
```

and you will get a little example that works:

![image](https://user-images.githubusercontent.com/165223/28564368-165f1d9e-7129-11e7-848d-23055cf5bb73.png)
